### ISSUE TITLE
issue pulling libscrc from pypi

### ISSUE THREAD

**Issue by guybw** [home-assistant/addons-development#18]
Hello,
I'm really stuck with an issue and wondered if anyone would be able to point me in the right direction.
One of my ha intergrations needs libscrc installed. I've tried pulling the library in with this addon but it fails every time.

Log below:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Remove old deps
[Info] Install pypi modules into deps
ERROR: Could not find a version that satisfies the requirement libscrc==1.6 (from versions: none)
ERROR: No matching distribution found for libscrc==1.6
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[Error] Can't install PyPI packages!
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

Is this a library issue or is it something I'm doing wrong?

My config is very simple....
`pypi:
  - libscrc==1.6
apk: []
`
Thanks!

**Comment by frenck** [comment]
I'm not sure why this is failing, to be honest, seems legit. However, I'm confused why you would use/need this add-on for that? Integrations can specify their dependencies and requirements in their manifest.

**Comment by guybw** [comment]
> I'm not sure why this is failing, to be honest, seems legit. However, I'm confused why you would use/need this add-on for that? Integrations can specify their dependencies and requirements in their manifest.

Thats what I thought however during boot up I get the error :

import libscrc
ModuleNotFoundError: No module named 'libscrc'
2021-02-21 17:32:03 ERROR (MainThread) [homeassistant.components.hassio] Component error: lux - Integration 'lux' not found.

The manifest.json file clearly has 
"requirements": ["libscrc==1.6"

Would you have any ideas on which way to go now?

**Comment by frenck** [comment]
Check the startup of Home Assistant Core, if there are hints for the reason it is not installing this package.

**Comment by guybw** [comment]
> Check the startup of Home Assistant Core, if there are hints for the reason it is not installing this package.

Thanks, it's the same issue, I guess I need to work out why the requirements don't download..
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 592, in _load_file
module = importlib.import_module(path)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/config/custom_components/lux/__init__.py", line 9, in <module>
from .LXPPacket import LXPPacket
File "/config/custom_components/lux/LXPPacket.py", line 2, in <module>
import libscrc
ModuleNotFoundError: No module named 'libscrc'
2021-02-21 17:43:55 ERROR (MainThread) [homeassistant.components.hassio] Component error: lux- Integration 'lux' not found.
