### ISSUE TITLE
Zigpy zigpi-znp

### ISSUE THREAD

**Issue by nielssteenvoorde** [home-assistant/addons-development#24]
I'am getting an error bij installing the zha integration with the development addons installed. 
In log files it looks like this:
_Logger: homeassistant.config_entries
Source: deps/lib/python3.9/site-packages/zigpy_znp/api.py:120
First occurred: 14:36:09 (2 occurrences)
Last logged: 14:38:46_

Error setting up entry TI CC2531 USB CDC, s/n: __xxxxxxxxxxx - Texas Instruments for zha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 102, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 152, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.9/site-packages/zigpy/application.py", line 69, in new
    await app.startup(auto_form)
  File "/config/deps/lib/python3.9/site-packages/zigpy_znp/zigbee/application.py", line 173, in startup
    return await self._startup(
  File "/config/deps/lib/python3.9/site-packages/zigpy_znp/zigbee/application.py", line 293, in _startup
    await self.load_network_info()
  File "/config/deps/lib/python3.9/site-packages/zigpy_znp/zigbee/application.py", line 1171, in load_network_info
    await self._znp.load_network_info(load_devices=load_devices)
  File "/config/deps/lib/python3.9/site-packages/zigpy_znp/api.py", line 120, in load_network_info
    network_info = zigpy.state.NetworkInformation(
TypeError: __init__() got an unexpected keyword argument 'children'

In configuration I used:
_pypi:
  - zha-quirks==0.0.38
apk: []_

And tried:
_pypi:
  - git+https://github.com/zigpy/zigpy-znp/_

Both same log file. Anyone the same problem when using a TI CC2531 stick with ZHA?

**Comment by frenck** [comment]
This is not an add-on issue, please report your issue with the `zigpy_znp` or related. 
The add-on simply tries to install the dependency, which fails because of non-add-on reasons.
